# Generated by Django 4.2.4 on 2023-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
