# Generated by Django 4.2.4 on 2023-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0002_alter_logmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=70)),
                ('dob', models.DateField(max_length=8)),
            ],
        ),
    ]
