# Generated by Django 4.2.4 on 2023-09-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0003_personadd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonAdd',
            new_name='Person',
        ),
    ]
