# Generated by Django 4.2.4 on 2023-09-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0004_rename_personadd_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parosmia.person'),
        ),
    ]
