# Generated by Django 4.2.7 on 2023-11-08 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0005_logmessage_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
