# Generated by Django 4.2.7 on 2023-11-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parosmia', '0006_remove_person_dob_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
