# Generated by Django 4.2.7 on 2023-11-09 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0007_alter_logmessage_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='sent_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
