# Generated by Django 4.2.7 on 2023-11-10 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parosmia', '0008_logmessage_sent_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('smells_like', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
