# Generated by Django 4.2.7 on 2023-11-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0009_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='log_date',
            field=models.DateTimeField(verbose_name='Experience Date'),
        ),
    ]
