# Generated by Django 4.2.7 on 2023-11-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0010_alter_experience_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='quantity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='smells_like',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
