# Generated by Django 4.2.7 on 2023-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parosmia', '0011_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
